import React, { useState, useEffect, useRef } from 'react';
import Router, { useRouter } from 'next/router';
import Head from 'next/head';
import axios from 'axios';
import { authUrl } from '../const/auth';
import styles from '../styles/Home.module.css';

const getTopTracks = async (artists, token, country) => {
  const promises = artists.map(artist =>
    axios
      .get(`https://api.spotify.com/v1/artists/${artist.id}/top-tracks`, {
        headers: { Authorization: `Bearer ${token}` },
        params: { market: country }
      })
      .then(({ data }) => data.tracks[0].uri)
  );

  return Promise.all(promises).then(responses => responses);

  // artists.reduce(async (acc, curr) => {
  //   console.log({ acc, curr });
  //   const topTracks = await axios.get(
  //     `https://api.spotify.com/v1/artists/${curr.id}/top-tracks`,
  //     {
  //       headers: { Authorization: `Bearer ${token}` },
  //       params: { market: country }
  //     }
  //   );

  //   console.log({ topTracks });
  //   return [...acc, topTracks.data.tracks[0].uri];
  // }, []);
};

const Home = () => {
  const router = useRouter();
  const clientToken = useRef(null);
  const [accessToken, setAccessToken] = useState(null);
  const [artist, setArtist] = useState(null);
  const [genres, setGenres] = useState(null);
  const [relatedArtists, setRelatedArtists] = useState(null);

  useEffect(() => {
    if (router.query.accessToken) {
      setAccessToken(router.query.accessToken);
      Router.push({ pathname: '/' });
    }
  }, []);

  useEffect(() => {
    if (accessToken) {
      const { sessionStorage } = window;
      const sessionArtist = sessionStorage.getItem('artist');
      const sessionGenres = sessionStorage.getItem('genres');
      const sessionRelatedArtists = sessionStorage.getItem('relatedArtists');
      if (sessionArtist) {
        setArtist(JSON.parse(sessionArtist));
      }
      if (sessionGenres) {
        setGenres(JSON.parse(sessionGenres));
      }
      if (sessionRelatedArtists) {
        setRelatedArtists(JSON.parse(sessionRelatedArtists));
      }
    }
  }, [accessToken]);

  useEffect(async () => {
    if (accessToken && relatedArtists) {
      axios
        .get('https://api.spotify.com/v1/me', {
          headers: { Authorization: `Bearer ${accessToken}` }
        })
        .then(({ data }) => {
          const { id, country } = data;
          axios
            .post(
              `https://api.spotify.com/v1/users/${id}/playlists`,
              { name: 'awesomeTestList' },
              { headers: { Authorization: `Bearer ${accessToken}` } }
            )
            .then(async ({ data }) => {
              const playListId = data.id;
              const tracks = await getTopTracks(
                relatedArtists,
                accessToken,
                country
              );
              console.log(JSON.parse(JSON.stringify(tracks)));
              axios
                .post(
                  `https://api.spotify.com/v1/playlists/${playListId}/tracks`,
                  { uris: tracks },
                  {
                    headers: { Authorization: `Bearer ${accessToken}` }
                  }
                )
                .then(res => console.log({ res }));
            });
        });
    }
  }, [accessToken, relatedArtists]);

  const getGenres = async artist => {
    console.log({ clientToken });
    const response = await axios.get(
      `https://api.spotify.com/v1/search?q=${artist}&type=artist`,
      {
        headers: {
          Authorization: `Bearer ${clientToken.current}`
        }
      }
    );

    if (response && response.status === 200) {
      setGenres(response.data.artists.items[0].genres);
      window.sessionStorage.setItem(
        'genres',
        JSON.stringify(response.data.artists.items[0].genres)
      );
    }
  };

  // set base url somewhere
  const getClientToken = () =>
    axios.get('http://localhost:3000/api/getClientToken').then(({ data }) => {
      clientToken.current = data.clientToken;
    });

  const getRelatedArtists = async genre => {
    // CHECK IF WE HAVE A CLIENTTOKEN
    const response = await axios({
      method: 'get',
      url: `https://api.spotify.com/v1/search?q=genre:%22${genre}%22&type=artist`,
      headers: {
        Authorization: `Bearer ${clientToken.current}`
      }
    });

    if (response && response.status === 200) {
      setRelatedArtists(response.data.artists.items);
      window.sessionStorage.setItem(
        'relatedArtists',
        JSON.stringify(response.data.artists.items)
      );
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Sups</h1>
        <form
          onSubmit={async e => {
            e.preventDefault();

            const form = new FormData(e.target);
            const formArtist = form.get('artist');
            setArtist(formArtist);
            window.sessionStorage.setItem('artist', JSON.stringify(formArtist));
            if (!clientToken.current) {
              await getClientToken();
            }

            await getGenres(formArtist);
          }}
        >
          <input name='artist' type='text' defaultValue={artist} required />
          <button type='submit'>search</button>
        </form>
        <ul>
          {genres &&
            genres.length &&
            genres.map(genre => (
              <li>
                <button type='button' onClick={() => getRelatedArtists(genre)}>
                  {genre}
                </button>
              </li>
            ))}
        </ul>
        <ul>
          {relatedArtists &&
            relatedArtists.map(artist => <li>{artist.name}</li>)}
          <button
            type='button'
            onClick={() => {
              window.location.href = authUrl('123');
            }}
          >
            create playlist
          </button>
        </ul>
      </main>

      <footer className={styles.footer}>
        <h2>Floop</h2>
      </footer>
    </div>
  );
};

export default Home;
