import React, { useState, useEffect, useRef } from 'react';
import Router, { useRouter } from 'next/router';
import Head from 'next/head';
import axios from 'axios';
import getTopTracks from '../helpers/get-top-tracks';
import getUserInfo from '../helpers/get-user-info';
import createPlayList from '../helpers/create-playlist';
import addTracksToPlaylist from '../helpers/add-tracks-to-playlist';
import getArtistInfo from '../helpers/get-artist-info';
import RelatedArtists from '../components/RelatedArtists';
import GenresList from '../components/GenresList';
import setSessionStorageItem from '../helpers/set-session-storage-item';
import Notification from '../components/Notification';
import getRelatedArtists from '../helpers/get-related-artists';

const getColors = () => {
  const colors = [
    ['#E50914', '#282581'],
    ['#FF0000', '#0A0D44'],
    ['#00FF8F', '#0A00A4'],
    ['#FFF300', '#E80000'],
    ['#00E8C5', '#5A009C'],
    ['#FF9E00', '#5A009C'],
    ['#FFEC00', '#FF00A6'],
    ['#51FF00', '#7400BF']
  ];
  return colors[Math.floor(Math.random() * 8)];
};

const getClientToken = clientToken =>
  axios.get('http://localhost:3000/api/getClientToken').then(({ data }) => {
    // eslint-disable-next-line no-param-reassign
    clientToken.current = data.clientToken;
  });

const Home = () => {
  const router = useRouter();
  const clientToken = useRef(null);
  const [accessToken, setAccessToken] = useState(null);
  const [artist, setArtist] = useState(null);
  const [genres, setGenres] = useState(null);
  const [selectedGenre, setSelectedGenre] = useState(null);
  const [relatedArtists, setRelatedArtists] = useState(null);
  const [notification, setNotification] = useState(null);
  const colors = getColors();

  useEffect(() => {
    if (router.query.accessToken) {
      setAccessToken(router.query.accessToken);
      Router.push('/#related', undefined, { shallow: true });
    }
  }, []);

  useEffect(() => {
    if (accessToken) {
      const { sessionStorage } = window;
      const sessionArtist = sessionStorage.getItem('artist');
      const sessionSelectedGenre = sessionStorage.getItem('selectedGenre');
      const sessionGenres = sessionStorage.getItem('genres');
      const sessionRelatedArtists = sessionStorage.getItem('relatedArtists');
      if (sessionSelectedGenre) {
        setSelectedGenre(JSON.parse(sessionSelectedGenre));
      }
      if (sessionArtist) {
        setArtist(JSON.parse(sessionArtist));
      }
      if (sessionGenres) {
        setGenres(JSON.parse(sessionGenres));
      }
      if (sessionRelatedArtists) {
        setRelatedArtists(JSON.parse(sessionRelatedArtists));
      }
    }
  }, [accessToken]);

  useEffect(async () => {
    if (accessToken && relatedArtists && selectedGenre) {
      getUserInfo({ accessToken, setNotification }).then(
        ({ id, country: market }) =>
          createPlayList({
            id,
            selectedGenre,
            accessToken,
            setNotification
          }).then(async ({ data: { id: playListId } }) => {
            const tracks = await getTopTracks({
              relatedArtists,
              accessToken,
              market,
              setNotification
            });
            addTracksToPlaylist({
              playListId,
              tracks,
              accessToken,
              setNotification
            });
          })
      );
    }
  }, [accessToken, relatedArtists, selectedGenre]);

  const onFormSubmit = async e => {
    e.preventDefault();

    const form = new FormData(e.target);
    const formArtist = form.get('artist');

    if (!clientToken.current) {
      await getClientToken(clientToken);
    }

    await getArtistInfo({
      formArtist,
      clientToken,
      setGenres,
      setNotification,
      setArtist
    });

    Router.push('/#genres', undefined, { shallow: true });
  };

  const onGenreClick = async genre => {
    setSelectedGenre(genre);
    setSessionStorageItem('selectedGenre', genre);

    if (!clientToken.current) {
      await getClientToken(clientToken);
    }

    await getRelatedArtists({
      genre,
      clientToken,
      setRelatedArtists,
      setNotification
    });

    Router.push('/#related', undefined, { shallow: true });
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link
          href='https://fonts.googleapis.com/css?family=Rubik:300,400,500'
          rel='stylesheet'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <section
          id='first-section'
          className='flex-container'
          style={{
            backgroundImage: `linear-gradient(transparent,#000), linear-gradient(90deg, ${colors[0]},${colors[1]})`
          }}
        >
          <div className='flex-item welcome-message'>
            <h3>Start browsing</h3>
            <h1>your music taste.</h1>
            <h2>What's your favourite artist's genre?</h2>
          </div>
          <div className='flex-item search-block'>
            <form onSubmit={onFormSubmit}>
              <input name='artist' type='text' defaultValue={artist} required />
              <button type='submit' style={{ backgroundColor: colors[1] }}>
                search
              </button>
            </form>
          </div>
        </section>
        <GenresList
          genres={genres}
          onGenreClick={onGenreClick}
          artist={artist}
          colors={colors}
        />
        <RelatedArtists
          genre={selectedGenre}
          colors={colors}
          artists={relatedArtists}
          relatedArtists={relatedArtists}
        />
        <Notification notification={notification} />
      </main>
    </div>
  );
};

export default Home;
